### ISSUE TITLE
Feature request: explicitly select events

### ISSUE THREAD

**Issue by kilianc** [segmentio/integration-slack#14]
The current behavior is to send everything to the default channel and use the integration settings to route particular events to channels.

It would be great if there was an "ingore all" option so that we explicitly say what we want and where.

**Comment by f2prateek** [comment]
We thought of this originally, but it just adds another place where users have too look to see if an event was disabled. The best place to do this is to disable events via the schema.

**Comment by kilianc** [comment]
The problem with the schema is that is blacklist only. Every time you track something new you need to filter it out from the integration.

Slack is a particular case, where you don't usually want everything poured into the channel but only few selected events.

I understand consistency is important. It may be worth to have a way to have a whitelist policy instead of blacklisting all events.

**Comment by f2prateek** [comment]
FWIW we have a catch all channel that gets all events (and nobody sits in this channel), and then we pipe each event into a specific channel since different teams want different events.

Events that are super high volume and overload slack's API limits get disabled in the schema.

We'll solve this more holistically with some product improvements, since Slack isn't the only tool affected by this limitation.

You might also check out https://relay.knowtify.io who we have an integration with if it suits your case better.

**Comment by kilianc** [comment]
Thanks a lot, they have a free tier, I'll give it a try!
